spring:
  datasource:
    url: jdbc:oracle:thin:@10.0.6.52:1521:aleph23
    username: CSM50
    password: CSM50
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true   
    hibernate:
      #ddl-auto: update      
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        #format_sql: true
        #dialect: org.hibernate.dialect.SQLServer2012Dialect
  jmx:
    default-domain: api-rest-biblio-prestamos   
# jmx importante para darle un identificador a jpa y funcionen varias apps en un tomcat    
  thymeleaf:
    cache: false
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        pdf: application/pdf

logging:
  level:
    org:  
      hibernate:
        #SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE