#server:
#  port : 8081
spring:
  datasource:
    url: jdbc:mysql://10.0.6.52/koha_library?useSSL=false
    username: koha_library
    password: vFFFv8EsxIN7GZ9E
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true   
    hibernate:
      #ddl-auto: update      
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #format_sql: true
        #dialect: org.hibernate.dialect.SQLServer2012Dialect
  jmx:
    default-domain: api-rest-biblio-prestamos   
# jmx importante para darle un identificador a jpa y funcionen varias apps en un tomcat    
  thymeleaf:
    cache: false
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        pdf: application/pdf

logging:
  level:
    org:  
      hibernate:
        #SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE